version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "10:00"
    target-branch: "develop"
    allow:
      - dependency-name: cookie
        update-types: ["minor", "patch", "major"]
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "10:00"
